services:
  express:
    command: npm run start
    ports:
      - "4000:3000"
    environment:
      - NODE_ENV=production
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${DOCKER_MONGODB_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${DOCKER_MONGODB_PASSWORD}
      - ME_CONFIG_MONGODB_URL=mongodb://${DOCKER_MONGODB_USERNAME}:${DOCKER_MONGODB_PASSWORD}@mongo:27017/
      - PORT=4000
