version: "3.4"
services:
  express:
    image: node:18-buster
    volumes:
      - type: bind
        source: ./
        target: /app
    working_dir: /app
    command: npm run dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
    restart: always
volumes:
  nodemodules:
